version: '3.4'

services:
  t2donlineconvert:
    image: t2donlineconvert
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/www/data:ro
    depends_on:
      - t2donlineconvert